name: Bug report
description: Report a bug you have found
title: "[Bug]: "
labels: 'bug'
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
  validations:
    required: true
- type: dropdown
  id: download
  attributes:
    label: where did you see this issue?
    options:
      - Web
      - API
      - Mobile
  validations:
    required: true
